CREATE FUNCTION `payBrandId`(`v` VARBINARY(32)) RETURNS SMALLINT UNSIGNED
BEGIN
DECLARE r BIGINT UNSIGNED;
SELECT id INTO r FROM payBrand WHERE payBrand.v=v;
IF r IS NULL THEN
INSERT INTO payBrand (v) VALUES (v);
RETURN LAST_INSERT_ID();
END IF;
RETURN r;
END ;;