CREATE FUNCTION `githubUserSet`(`id` BIGINT UNSIGNED,`uid` BIGINT UNSIGNED) RETURNS TINYINT UNSIGNED
    DETERMINISTIC
BEGIN
IF EXISTS(SELECT 1 FROM githubUser g WHERE g.uid=uid) THEN RETURN 2; END IF;
UPDATE githubUser g SET g.uid=uid WHERE g.id=id AND g.uid=0;
RETURN IF(ROW_COUNT()=1,0,1);
END ;;