CREATE TABLE `authHardware` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`authWidthHeightId` BIGINT UNSIGNED DEFAULT NULL,`pixelRatio` TINYINT UNSIGNED DEFAULT NULL,`cpu` SMALLINT UNSIGNED DEFAULT NULL,`authGpuId` BIGINT UNSIGNED DEFAULT NULL,`authArchId` BIGINT UNSIGNED DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `unqiue` (`authWidthHeightId`,`pixelRatio`,`cpu`,`authGpuId`,`authArchId`)
);