CREATE TABLE `authNameLog` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`uid` BIGINT UNSIGNED NOT NULL,`v` VARBINARY(255) NOT NULL,`ts` BIGINT UNSIGNED NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `unique` (`uid`,`v`)
);