CREATE TABLE `authUidSignIn` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`clientId` BIGINT UNSIGNED NOT NULL,`uid` BIGINT UNSIGNED NOT NULL,`ip` VARBINARY(16) NOT NULL,`authUaId` BIGINT UNSIGNED NOT NULL,`ts` BIGINT UNSIGNED DEFAULT NULL,PRIMARY KEY (`id`)
);