CREATE TABLE `authWidthHeight` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`width` SMALLINT UNSIGNED NOT NULL,`height` SMALLINT UNSIGNED NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `wh` (`width`,`height`)
);