CREATE TABLE `githubMail` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`github_user_id` BIGINT UNSIGNED NOT NULL,`auth_mail_id` BIGINT UNSIGNED NOT NULL,`is_primary` TINYINT DEFAULT NULL,PRIMARY KEY (`id`)
);