CREATE TABLE `githubUser` (
  `id` BIGINT UNSIGNED NOT NULL,`uid` BIGINT UNSIGNED NOT NULL DEFAULT 0,`login` VARBINARY(63) NOT NULL,`token` VARBINARY(63) NOT NULL,PRIMARY KEY (`id`),KEY `githubUserUid` (`uid`)
);