[package]
name = "tmpl"
version = "0.1.0"
edition = "2021"

[dependencies]
client = { path = "../../../rust/lib/client" }
prost = "0.13.3"
re = "0.1.9"
t3 = "0.1.20"

[build-dependencies]
aok = "0.1.15"
prost-build = "0.13.3"

[package.metadata.cargo-machete]
ignored = ["prost"]
