CREATE TABLE `payExchangeRate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`v` BIGINT UNSIGNED NOT NULL,`day` SMALLINT UNSIGNED NOT NULL,`f` SMALLINT UNSIGNED NOT NULL,`t` SMALLINT UNSIGNED NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `day` (`f`,`t`,`day`)
);