CREATE TABLE `payStripeTopup` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`v` VARBINARY(32) NOT NULL,`currency_id` SMALLINT UNSIGNED NOT NULL,`n` BIGINT UNSIGNED NOT NULL,`recv` BIGINT UNSIGNED NOT NULL DEFAULT 0,`rate` BIGINT UNSIGNED NOT NULL,`status` TINYINT UNSIGNED NOT NULL,`uid` BIGINT UNSIGNED NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `v` (`v`)
);