CREATE TABLE `token` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`uid` BIGINT UNSIGNED NOT NULL,`ts` BIGINT UNSIGNED NOT NULL,`name` VARBINARY(255) NOT NULL DEFAULT '',`enable` TINYINT NOT NULL DEFAULT 1,PRIMARY KEY (`id`),KEY `uid` (`uid`)
);