CREATE FUNCTION `authArchId`(v VARBINARY(255)) RETURNS INT UNSIGNED
BEGIN
  DECLARE r BIGINT UNSIGNED;
  SELECT id INTO r FROM authArch WHERE authArch.v=v;
  IF r IS NULL THEN
    INSERT INTO authArch (v) VALUES (v);
    RETURN LAST_INSERT_ID();
END IF;
RETURN r;
END ;;