CREATE FUNCTION `authBrowserId`(v VARBINARY(255)) RETURNS INT UNSIGNED
BEGIN
  DECLARE r BIGINT UNSIGNED;
  SELECT id INTO r FROM authBrowser WHERE authBrowser.v=v;
  IF r IS NULL THEN
    INSERT INTO authBrowser (v) VALUES (v);
    RETURN LAST_INSERT_ID();
END IF;
RETURN r;
END ;;