CREATE FUNCTION `authLangId`(v VARBINARY(255)) RETURNS INT UNSIGNED
BEGIN
  DECLARE r BIGINT UNSIGNED;
  SELECT id INTO r FROM authLang WHERE authLang.v=v;
  IF r IS NULL THEN
    INSERT INTO authLang (v) VALUES (v);
    RETURN LAST_INSERT_ID();
END IF;
RETURN r;
END ;;