CREATE FUNCTION `authMailId`(`mail` VARBINARY(255)) RETURNS BIGINT UNSIGNED
BEGIN
DECLARE h BIGINT UNSIGNED;
CALL splitMail(mail,@u,@h);
SELECT id INTO h FROM authMailHost WHERE v=@h;
IF h IS NULL THEN
RETURN NULL;
END IF;
RETURN (SELECT id FROM authMail WHERE usr=@u AND hostId=h);
END ;;