CREATE FUNCTION `authMailHostId`(v VARBINARY(255)) RETURNS BIGINT UNSIGNED
BEGIN
  DECLARE r BIGINT UNSIGNED;
  SELECT id INTO r FROM authMailHost WHERE authMailHost.v=v;
  IF r IS NULL THEN
    INSERT INTO authMailHost (v) VALUES (v);
    RETURN LAST_INSERT_ID();
  END IF;
RETURN r;
END ;;