CREATE FUNCTION `authNameId`(v VARBINARY(255)) RETURNS BIGINT UNSIGNED
BEGIN
  DECLARE r BIGINT UNSIGNED;
  SELECT id INTO r FROM authName WHERE authName.v=v;
  IF r IS NULL THEN
    INSERT INTO authName (v) VALUES (v);
    RETURN LAST_INSERT_ID();
  END IF;
RETURN r;
END ;;