CREATE FUNCTION `authNameLog`(uid BIGINT UNSIGNED,name VARBINARY(255)) RETURNS TINYINT
BEGIN
INSERT INTO authNameLog (uid,v,ts)VALUES(uid,name,unix_timestamp()) ON DUPLICATE KEY UPDATE ts=VALUES(ts);
RETURN NULL;
END ;;