CREATE FUNCTION `authUidMail`(`uid` BIGINT UNSIGNED) RETURNS VARBINARY(255)
BEGIN
 DECLARE id BIGINT UNSIGNED;
 DECLARE mail VARBINARY(255);
 SELECT authMailId INTO id FROM authUidMail t WHERE t.id=uid;
 IF id IS NULL THEN
   RETURN "";
 END IF;
 SELECT authIdMail(id) INTO mail;
 RETURN mail;
END ;;