CREATE FUNCTION `authWidthHeightId`(w SMALLINT UNSIGNED,h SMALLINT UNSIGNED) RETURNS BIGINT UNSIGNED
BEGIN
  DECLARE r BIGINT UNSIGNED;
  SELECT id INTO r FROM authWidthHeight WHERE width=w AND height=h;
  IF r IS NULL THEN
    INSERT INTO authWidthHeight(width,height) VALUES(w,h);
    RETURN LAST_INSERT_ID();
  END IF;
RETURN r;
END ;;