CREATE TABLE `webpush` (
  `id` BIGINT UNSIGNED NOT NULL,`hostId` BIGINT UNSIGNED NOT NULL,`endpointHostId` INT UNSIGNED NOT NULL,`endpoint` VARBINARY(255) NOT NULL,`auth` BINARY(16) NOT NULL,`p256dh` BINARY(65) NOT NULL,`lang` SMALLINT UNSIGNED NOT NULL,KEY `hostId` (`hostId`)
);